Output use_server.gif

Require uv 

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600

Set Shell fish
Sleep 1s
Type "uv run use_server.py"
Sleep 500ms
Right
Enter
Sleep 1.5s
Type "Hiiiii"
Enter
Sleep 1.5s
Escape
Type "uv run use_server.py"
Sleep 500ms
Enter
Sleep 1s
Type "How are ya?"
Sleep 500ms
Enter
Sleep 2s
Escape
Type "uv run use_server.py"
Sleep 500ms
Enter
Sleep 1s
Type "Where's my order?"
Sleep 500ms
Enter
Sleep 3s
